# Copyright 2025.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pattern:
  default:
    - input: "dataverse-platform-([a-z0-9]+)"
      output: "$1_group"

    - input: "dataverse-source-([a-z0-9]+)"
      output: "$1_group"

    - input: "dataverse-aggregate-([a-z0-9]+)"
      output: "$1_group"

    - input: "dataverse-consumer-([a-z0-9]+-[a-z0-9]+)"
      output: "$1|replace(-,_)_group"

  rover:
    - input: "^([^\\_]+)$"
      output: "$1"


app:
  name: "usernaut"
  version: "0.0.1"
  environment: "default"
  debug: true

ldap:
  server: "ldap://ldap.test.com:389"
  baseDN: "ou=adhoc,ou=managedGroups,dc=org,dc=com"
  userDN: "uid=%s,ou=users,dc=org,dc=com"
  userSearchFilter: "(objectClass=filterClass)"
  attributes: ["mail", "uid", "cn", "sn", "displayName"]

cache:
  driver: "memory"
  inmemory:
    defaultExpiration: -1
    cleanupInterval: -1
  redis:
    host: localhost
    port: "6379"
    database: 0
    password: ""

httpClient:
  connectionPoolConfig:
    timeout: 10000
    keepAliveTimeout: 600000
    maxIdleConnections: 10
  hystrixResiliencyConfig:
    maxConcurrentRequests: 100
    requestVolumeThreshold: 20
    circuitBreakerSleepWindow: 5000
    errorPercentThreshold: 50
    circuitBreakerTimeout: 10000

backends:
  - name: fivetran
    type: "fivetran"
    enabled: true
    connection:
      apiKey: file|/path/to/fivetran_key
      apiSecret: file|/path/to/fivetran_secret
  - name: rover
    type: "rover"
    enabled: true
    connection:
      url: "https://rover.test.com"
      cert_path: "file|/path/to/usernaut.crt"
      private_key_path: "file|/path/to/usernaut.pem"
      service_account_name: test-service-account
  - name: test
    type: "snowflake"
    enabled: true
    connection: 
      pat: file|/path/to/SNOWFLAKE_PAT
      base_url: https://myorganization-myaccount.snowflakecomputing.com

apiServer:
  address: "0.0.0.0:8080"
  auth:
    enabled: true
    basic_users:
      - username: "app1"
        password: env|APP1_PASSWORD

  cors:
    allowed_origins: ["http://localhost:3000", "http://localhost:8080"]
